# HW5

For this homework, we are going to work with [*Indoor User Movement Prediction from RSS data*](https://archive.ics.uci.edu/ml/datasets/Indoor+User+Movement+Prediction+from+RSS+data) dataset from UCI.  The homework is due Friday, December 21st midnight. 

## Task 1

Download the dataset and unzip it in under a subdirectory of `data` folder named `rss_data`.

The files we are interested is in the subfolder `dataset`.  Each of these files whose names that start with `MovementAAL_RSS_` contain data collected from indivuduals. Each of these files represent a single data point.  There are 314 of these files, and hence, you have 314 data points.  Each file has 4 columns but the number of rows change from file to file.  

There is also a file named `MovementALL_target.csv` in that folder. This file tells us the class each of these measurements are assigned. Some of these measurements are labelled with +1 and some are labelled with -1.

## Task 2

Construct a SVM model that separates +1 labelled data points from -1 data points.  You must first solve the problem that these datapoints do not have the same number of rows even though they all have the same number of columns. 

## Task 3

Using [Keras](https://keras.io/getting-started/sequential-model-guide/) write a neural network model that separates +1 labelled data points from -1 data points.

## Notes

1. You must document each step of your tasks: what are you doing, why are you doing it, what problems you encountered and how you solved it.  All of these must be explained and documented.  Solutions without sufficient documentations will be penalized accordingly. 50% of your points will come from your code, while the other 50% will come from your explanations.

1. You can use MS Excel to inspect the files, but loading them up to python using pandas and inspecting them there under jupyter is easier.

3. Put the data in a separate subfolder of your `data` folder and rename it `rss_data`. I'll take points off if the data is not saved under the correct place.

1. For both of Task 2 and Task 3, you must split your data into a train and test set, and then evaluate the accuracy of your model on the test set.

# SUPPORT VECTOR MACHINE

In [2]:
# First import libraries
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt

In [3]:
movedata = pd.read_csv('../data/rss_data/MovementAAL_target.csv', names=('sequence_ID', 'class_label'))

FileNotFoundError: File b'../data/rss_data/MovementAAL_target.csv' does not exist

In [28]:
movedata

     #sequence_ID   class_label
0               1             1
1               2             1
2               3             1
3               4             1
4               5             1
5               6             1
6               7             1
7               8             1
8               9             1
9              10             1
10             11             1
11             12             1
12             13             1
13             14             1
14             15             1
15             16             1
16             17             1
17             18             1
18             19             1
19             20             1
20             21             1
21             22             1
22             23             1
23             24             1
24             25             1
25             26             1
26             27            -1
27             28            -1
28             29            -1
29             30            -1
..            ...           ...
284           285             1
285           286             1
286           287             1
287           288             1
288           289             1
289           290             1
290           291             1
291           292             1
292           293             1
293           294             1
294           295             1
295           296             1
296           297             1
297           298             1
298           299             1
299           300             1
300           301             1
301           302            -1
302           303            -1
303           304            -1
304           305            -1
305           306            -1
306           307            -1
307           308            -1
308           309            -1
309           310            -1
310           311            -1
311           312            -1
312           313            -1
313           314            -1

[314 rows x 2 columns]

In [17]:
X = movedata.iloc[:,0]
y = movedata.iloc[:,1]

In [29]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [34]:
X = X.reshape(-1,1)

In [42]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear', C = 1.0)  
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [45]:
y_pred = svclassifier.predict(X_test)

In [46]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[16, 18],
       [15, 14]])

NameError: name 'accuracy' is not defined

# KERAS

In [47]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential()
model.add(Dense(32, input_dim=784))
model.add(Activation('relu'))

Using TensorFlow backend.

In [ ]:
# For a binary classification problem
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(xs,ys,test_size=0.25)

NameError: name 'xs' is not defined

In [50]:
movedata_keras

     #sequence_ID   class_label
0               1             1
1               2             1
2               3             1
3               4             1
4               5             1
5               6             1
6               7             1
7               8             1
8               9             1
9              10             1
10             11             1
11             12             1
12             13             1
13             14             1
14             15             1
15             16             1
16             17             1
17             18             1
18             19             1
19             20             1
20             21             1
21             22             1
22             23             1
23             24             1
24             25             1
25             26             1
26             27            -1
27             28            -1
28             29            -1
29             30            -1
..            ...           ...
284           285             1
285           286             1
286           287             1
287           288             1
288           289             1
289           290             1
290           291             1
291           292             1
292           293             1
293           294             1
294           295             1
295           296             1
296           297             1
297           298             1
298           299             1
299           300             1
300           301             1
301           302            -1
302           303            -1
303           304            -1
304           305            -1
305           306            -1
306           307            -1
307           308            -1
308           309            -1
309           310            -1
310           311            -1
311           312            -1
312           313            -1
313           314            -1

[314 rows x 2 columns]

In [ ]:
X = movedata.iloc[:,0]
y = movedata.iloc[:,1]

In [ ]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)